version: '3.9'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-homecare}
      POSTGRES_USER: ${DB_USER:-dev}
      POSTGRES_PASSWORD: ${DB_PASS:-devpass}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: dart:stable
    working_dir: /app
    volumes:
      - ./homecare_backend:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-homecare}
      DB_USER: ${DB_USER:-dev}
      DB_PASS: ${DB_PASS:-devpass}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-change-me-access}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-change-me-refresh}
      PORT: ${PORT:-8080}
    depends_on:
      - db
    command: bash -c "dart pub get && dart run bin/server.dart"
    ports:
      - "${PORT:-8080}:8080"

volumes:
  pgdata:
