name: mock_server
description: A mock server for the HomeCare app.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  postgres: ^2.6.1
  dargon2_flutter: ^2.1.2
  dart_jsonwebtoken: ^2.12.0

dev_dependencies:
  lints: ^3.0.0
