name: homecare_backend
description: A server-side application for the HomeCare project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  postgres: ^3.1.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  shelf_cors_headers: ^0.1.5
  dart_jsonwebtoken: ^2.12.0
  bcrypt: ^1.1.3
  uuid: ^3.0.7
  crypto: ^3.0.3
  qr: ^3.0.1
  image: ^4.1.7
  socket_io:
    path: third_party/socket_io

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  stream_channel: ^2.1.4
  mocktail: ^1.0.3
