name: homecare_app
description: HomeCare - Ứng dụng quản lý việc nhà (Flutter)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core & State Management
  flutter_bloc: ^9.1.1
  get_it: ^7.7.0
  equatable: ^2.0.7

  # Networking & Storage
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^7.0.0
  socket_io_client: ^3.1.2

  # Firebase & Notifications
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^17.2.1

  # UI & UX
  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  flutter_slidable: ^2.0.0
  cached_network_image: ^3.4.1

  # Hardware & Permissions
  permission_handler: ^12.0.1
  mobile_scanner: ^7.1.2
  image_picker: ^1.2.0
  flutter_image_compress: ^2.4.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code generation & debugging
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  pretty_dio_logger: ^1.3.1 # For logging network calls
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  #assets:
  #  - assets/images/
